import { mkdir, writeFile } from 'node:fs/promises';
import { routes, openapiDocument } from '../packages/contracts/routes';
import { mobileFixtures } from '../packages/contracts/fixtures';

async function main() {
  await mkdir('packages/contracts/generated',{recursive:true});
  await writeFile('packages/contracts/generated/openapi.json',JSON.stringify(openapiDocument(),null,2)+'\n');
  const cases=routes.map(r=>`    case ${r.operation}`).join('\n');
  const path=routes.map(r=>`        case .${r.operation}: return ${JSON.stringify(r.path)}`).join('\n');
  const methods=routes.map(r=>`        case .${r.operation}: return ${JSON.stringify(r.method)}`).join('\n');
  const access=routes.map(r=>`        case .${r.operation}: return ${'public' in r ? 'true' : 'false'}`).join('\n');
  await mkdir('apps/ios/Sources/Generated',{recursive:true});
  await writeFile('apps/ios/Sources/Generated/APIOperation.swift',`// Generated by npm run contracts. Do not edit.\nimport Foundation\n\nenum APIOperation: String, Codable, Sendable {\n${cases}\n    var path: String {\n        switch self {\n${path}\n        }\n    }\n    var method: String {\n        switch self {\n${methods}\n        }\n    }\n    var isPublic: Bool {\n        switch self {\n${access}\n        }\n    }\n}\n`);
  await mkdir('apps/ios/Tests/Fixtures',{recursive:true});
  for(const [name,body] of Object.entries(await mobileFixtures())) await writeFile(`apps/ios/Tests/Fixtures/${name}.json`,JSON.stringify(body,null,2)+'\n');
  console.log('OpenAPI 3.1, Swift operation bindings and service-backed fixtures generated');
}
void main();
